version: '2'

services:

  tensorflow:
    build: .
    entrypoint: ["/usr/bin/python3", "genetic.py"]
    environment:
      - "MODELS_DIR=/models"
    volumes:
      - model-volume:/models/
      - ./submissions:/submissions

  tensorboard:
    build: .
    ports:
      - "80:6006"
      - "8080:8080"
    expose:
      - 8080
    volumes:
      - model-volume:/models/
    entrypoint: ["tensorboard",  "--logdir=/models/", "--host=0.0.0.0", "--port=6006", "--debugger_port", "8080"]

volumes:
  model-volume: